[package]
name = "ptsl-extras"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
ptsl-client = { version = "=0.1", path = "../ptsl-client" }
ptsl-protos = { version = "=0.1", path = "../ptsl-protos" }
