[package]
name = "ptsl-future"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
pin-project-lite = { version = "0.2", default-features = false }
tokio = { version = "1.33", default-features = false, features = ["time"] }
