[package]
name = "ptsl-protos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[build-dependencies]
tonic-build = { version = "0.10", default-features = false, features = ["prost"] }
